---
language: python
services: docker

env:
  global: []
  matrix:
    - MOLECULE_DISTRO: "ubuntu1804"

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script: []


script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
