---
- name: 'Prepare server for Odoo installation'
  block:

    - name: 'Add BrightBox Ruby Repository'
      apt_repository:
        repo: "ppa:brightbox/ruby-ng"
        state: present

    - name: 'Create Odoo system user'
      user:
        name: "{{ odoo_user }}"
        home: "{{ odoo_base_path }}"
        group: "{{ odoo_user }}"
        system: yes
        move_home: yes

    - name: 'Ensure required directories are present'
      file:
        path: "{{ item }}"
        state: directory
        mode: 0644
        owner: "{{ odoo_user }}"
      with_items:
        - "{{ odoo_install_path }}"
        - "{{ odoo_addons_path }}"
        - "{{ odoo_addons_repos_path }}"
        - "{{ odoo_log_path }}"

  tags:
    - odoo_repositories
    - odoo_install
