---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
    published_ports:
      - 8069:8069
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  lint_sequence:
    - lint
