---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible (Ubuntu)
      become: true
      raw: > 
        test -e /usr/bin/python || 
        (apt -y update && apt install -y python-minimal python-zipstream)
      when: ansible_user == 'ubuntu'
      changed_when: false

- name: Install PostgreSQL from geerlingguy.postgresql
  hosts: all
  become: yes
  vars:
    postgresql_databases:
      - name: "odoo"
    postgresql_users:
      - name: "odoo"
        password: "password"
  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: 'Install required packages for apt-key to work'
      apt:
        name: gpg-agent
        state: present
      changed_when: false

  roles:
    - role: geerlingguy.postgresql
