---
- name: Install PostgreSQL from geerlingguy.postgresql
  hosts: all
  become: yes
  vars:
    postgresql_databases:
      - name: "odoo"
    postgresql_users:
      - name: "odoo"
        password: "password"
  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: 'Install required packages for apt-key to work'
      apt:
        name: gpg-agent
        state: present

  roles:
    - role: geerlingguy.postgresql
